
DROP DATABASE IF EXISTS TWEETS;
CREATE DATABASE TWEETS;

USE TWEETS;

DROP USER IF EXISTS twitter;
CREATE USER twitter IDENTIFIED WITH mysql_native_password BY 'password' REQUIRE NONE;
GRANT ALL ON TWEETS.* TO twitter;

FLUSH PRIVILEGES;

