
DROP DATABASE IF EXISTS TWEETSTEST;
CREATE DATABASE TWEETSTEST;

USE TWEETSTEST;

DROP USER IF EXISTS twitter;
CREATE USER twitter IDENTIFIED WITH mysql_native_password BY 'password' REQUIRE NONE;
GRANT ALL ON TWEETSTEST.* TO twitter;

FLUSH PRIVILEGES;

